### ISSUE TITLE
Can’t vote in World Assembly

### ISSUE THREAD

**Issue by reeceicles** [bart-kneepkens/Issues#1] opened 2021-02-20 13:03 UTC
I vote in the app for WA resolutions, but this doesn’t carry over when I go check on the website, and my vote soon disappears from the app too.

**Comment by bart-kneepkens** [comment] 2021-02-20 13:10
Hey, thanks for letting me know. Could you let me know which resolution you are trying to vote on? Does it happen more often?

**Comment by reeceicles** [comment] 2021-02-20 13:13
It won’t work with either current resolution, and I’ve never been able to vote on a resolution in the app before, because it’s never worked.

**Comment by bart-kneepkens** [comment] 2021-02-20 13:41
Okay.. Sounds like something is not going right on the authentication side. I'm not able to reproduce the issue at this time. 

Can you let me know if you can read the resolution 'contents' properly?
And have you tried signing out, then closing the app, and signing in? That might solve the issue, not sure.

**Closed as not planned** 2023-10-14 15:15 UTC
